### ISSUE TITLE
Go back to normal github when clicking the button again

### ISSUE THREAD

**Issue by Alxandr** [git-toni/reposplit#3]
This is great, but I'd like to go back to normal github when I click the button for a second time. Whether this is done by magic or a simple reload isn't too important though.

**Comment by git-toni** [comment]
@Alxandr That's a good idea. Right now you just need to click on the repo name link, and it will reload to normal GH. Would this solve the feature for you? Or is it more straight-forward to have the same button Enable/Disable?

**Comment by Alxandr** [comment]
Probably both. I discovered the ability to click the repo link after I posted this, but I also think it would be intuitive to have the button work as a toggle.

**Comment by git-toni** [comment]
This should be working as you suggested now!
