### ISSUE TITLE
Does not work if you're not on default branch.

### ISSUE THREAD

**Issue by Alxandr** [git-toni/reposplit#4]
I just tried clicking the button from this url: https://github.com/callemall/material-ui/tree/next

The result is not what you'd expect :P, the file list shows up in the right column and the left column is just empty.

**Comment by git-toni** [comment]
@Alxandr I just tried it from that url and it works "fine" for me. By fine I mean that it lets you browse the **master** branch of that repository. Of course I guess you wouldn't want that - you'd like the **next** - branch. I will add that feature - other branches browsing - to the TODO. :)

**Comment by Alxandr** [comment]
This is what I get:

![image](https://cloud.githubusercontent.com/assets/112334/25582181/2c9e0140-2e8c-11e7-9eb7-a4e0961a463a.png)

Notice the huge wasted space on the left.

**Comment by git-toni** [comment]
Thanks for reporting this, I'll try to reproduce it. What OS/Chrome version is that? Also, does it happen with any other repository, or just with that repo *and* branch?

**Comment by Alxandr** [comment]
Same happens here: https://github.com/Alxandr/inferno/tree/feature-redux

I'm on OSX chrome version 57.

**Comment by git-toni** [comment]
Hi @Alxandr,

I don't have access to an OSX machine. However I tried to reproduce your problem on versions 56, 57, 58 but no luck :( 
My guess is that it has to do with some of the dynamic styling going on, so I tried to position things a bit more explicitly, instead of letting the browser decide some positions. Let me know if these changes help in any way in `v0.1.1`.

Also, now one can browse repo branches other than `master`.

**Comment by Alxandr** [comment]
Gret. Positioning issue is fixed. I still can't seem to browse other branches though. Also, you should show current branch name under the repo-name.

**Comment by git-toni** [comment]
@Alxandr Actually, the current branch name should be shown right under the repo name as you say. I'm happy to hear positioning is fixed  :+1:

**Comment by Alxandr** [comment]
Hmm, the extension should auto-update, right?

**Comment by git-toni** [comment]
Could you confirm you have `v.0.1.2` @ `chrome://extensions`? Chrome Dev Dashboard informed me it could take up to 60miin to appear on the store. Although in principle it should auto-update, yes.

**Comment by Alxandr** [comment]
I have `0.1`. I'll check again later.

**Comment by Alxandr** [comment]
Perfect. Works.
